name: Update README on Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update VERSION block in README
      run: |
        TAG_NAME="${{ github.event.release.tag_name }}"
        RELEASE_DATE=$(date +"%d %B %Y")
        
        # Mettre à jour le bloc VERSION dans README.md
        sed -i "s|<!--VERSION-START-->.*Version actuelle.*|<!--VERSION-START-->\n**Version actuelle (latest):** $TAG_NAME ⭐|" README.md
        sed -i "s|Date de release :.*|**Date de release :** $RELEASE_DATE|" README.md
        
        echo "✅ README mis à jour avec version $TAG_NAME"
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        if git diff --quiet README.md; then
          echo "Aucun changement à commiter"
        else
          git add README.md
          git commit -m "docs: auto-update README with release ${{ github.event.release.tag_name }}"
          git push
          echo "✅ README poussé vers main"
        fi

